import { Category } from '../types/expense';

// Comprehensive keyword → category map for Indian users
const KEYWORD_MAP: Record<string, Category> = {
  // ── Food & Dining ──────────────────────────────────────────
  food: 'Food & Dining',
  lunch: 'Food & Dining',
  dinner: 'Food & Dining',
  breakfast: 'Food & Dining',
  snack: 'Food & Dining',
  chai: 'Food & Dining',
  tea: 'Food & Dining',
  coffee: 'Food & Dining',
  cafe: 'Food & Dining',
  restaurant: 'Food & Dining',
  biryani: 'Food & Dining',
  pizza: 'Food & Dining',
  burger: 'Food & Dining',
  sandwich: 'Food & Dining',
  dosa: 'Food & Dining',
  idli: 'Food & Dining',
  paratha: 'Food & Dining',
  roti: 'Food & Dining',
  dal: 'Food & Dining',
  sabzi: 'Food & Dining',
  curry: 'Food & Dining',
  noodles: 'Food & Dining',
  pasta: 'Food & Dining',
  chinese: 'Food & Dining',
  sushi: 'Food & Dining',
  hotel: 'Food & Dining',
  dhaba: 'Food & Dining',
  swiggy: 'Food & Dining',
  zomato: 'Food & Dining',
  maggi: 'Food & Dining',
  juice: 'Food & Dining',
  lassi: 'Food & Dining',
  shake: 'Food & Dining',
  thali: 'Food & Dining',
  vada: 'Food & Dining',
  pav: 'Food & Dining',
  samosa: 'Food & Dining',
  kachori: 'Food & Dining',
  chaat: 'Food & Dining',
  pani: 'Food & Dining',
  chole: 'Food & Dining',
  rajma: 'Food & Dining',
  momos: 'Food & Dining',
  wrap: 'Food & Dining',
  kfc: 'Food & Dining',
  mcd: 'Food & Dining',
  mcdonalds: 'Food & Dining',
  dominos: 'Food & Dining',
  subway: 'Food & Dining',
  ccd: 'Food & Dining',
  starbucks: 'Food & Dining',
  dunkin: 'Food & Dining',
  barbeque: 'Food & Dining',
  bbq: 'Food & Dining',
  icecream: 'Food & Dining',
  dessert: 'Food & Dining',
  cake: 'Food & Dining',
  pastry: 'Food & Dining',
  chocolate: 'Food & Dining',
  eat: 'Food & Dining',
  meal: 'Food & Dining',
  tiffin: 'Food & Dining',
  mess: 'Food & Dining',
  canteen: 'Food & Dining',
  water: 'Food & Dining',
  bisleri: 'Food & Dining',
  kinley: 'Food & Dining',
  soda: 'Food & Dining',
  cold: 'Food & Dining',
  drink: 'Food & Dining',
  pepsi: 'Food & Dining',
  coke: 'Food & Dining',
  limca: 'Food & Dining',
  sprite: 'Food & Dining',
  thums: 'Food & Dining',

  // ── Groceries ─────────────────────────────────────────────
  grocery: 'Groceries',
  groceries: 'Groceries',
  vegetables: 'Groceries',
  sabji: 'Groceries',
  sabzimandi: 'Groceries',
  fruits: 'Groceries',
  flour: 'Groceries',
  atta: 'Groceries',
  rice: 'Groceries',
  sugar: 'Groceries',
  salt: 'Groceries',
  oil: 'Groceries',
  ghee: 'Groceries',
  milk: 'Groceries',
  paneer: 'Groceries',
  eggs: 'Groceries',
  chicken: 'Groceries',
  mutton: 'Groceries',
  fish: 'Groceries',
  ration: 'Groceries',
  kirana: 'Groceries',
  dmart: 'Groceries',
  blinkit: 'Groceries',
  zepto: 'Groceries',
  bigbasket: 'Groceries',
  reliance: 'Groceries',
  more: 'Groceries',
  spices: 'Groceries',
  masala: 'Groceries',
  lentil: 'Groceries',
  supermarket: 'Groceries',
  market: 'Groceries',
  mandi: 'Groceries',
  butter: 'Groceries',
  cheese: 'Groceries',
  curd: 'Groceries',
  dahi: 'Groceries',
  bread: 'Groceries',

  // ── Transport ──────────────────────────────────────────────
  auto: 'Transport',
  rickshaw: 'Transport',
  uber: 'Transport',
  ola: 'Transport',
  rapido: 'Transport',
  bus: 'Transport',
  metro: 'Transport',
  train: 'Transport',
  cab: 'Transport',
  taxi: 'Transport',
  bike: 'Transport',
  petrol: 'Transport',
  diesel: 'Transport',
  fuel: 'Transport',
  parking: 'Transport',
  toll: 'Transport',
  ferry: 'Transport',
  flight: 'Transport',
  airport: 'Transport',
  irctc: 'Transport',
  railway: 'Transport',
  travel: 'Transport',
  commute: 'Transport',
  ride: 'Transport',
  share: 'Transport',
  vehicle: 'Transport',
  servicing: 'Transport',
  repair: 'Transport',
  tyre: 'Transport',
  puncture: 'Transport',
  indigo: 'Transport',
  spicejet: 'Transport',
  airindia: 'Transport',
  vistara: 'Transport',
  redbus: 'Transport',
  ticket: 'Transport',
  pass: 'Transport',

  // ── Health ─────────────────────────────────────────────────
  medicine: 'Health',
  medicines: 'Health',
  medical: 'Health',
  pharmacy: 'Health',
  doctor: 'Health',
  hospital: 'Health',
  clinic: 'Health',
  chemist: 'Health',
  tablet: 'Health',
  tablets: 'Health',
  capsule: 'Health',
  syrup: 'Health',
  injection: 'Health',
  vaccine: 'Health',
  test: 'Health',
  checkup: 'Health',
  xray: 'Health',
  blood: 'Health',
  lab: 'Health',
  pathlab: 'Health',
  apollo: 'Health',
  fortis: 'Health',
  aiims: 'Health',
  max: 'Health',
  medanta: 'Health',
  netmeds: 'Health',
  pharmeasy: 'Health',
  tata1mg: 'Health',
  strepsils: 'Health',
  dolo: 'Health',
  paracetamol: 'Health',
  crocin: 'Health',
  combiflam: 'Health',
  azithromycin: 'Health',
  amoxicillin: 'Health',
  antibiotic: 'Health',
  vitamin: 'Health',
  supplement: 'Health',
  protein: 'Health',
  bandage: 'Health',
  sanitizer: 'Health',
  gym: 'Health',
  yoga: 'Health',
  fitness: 'Health',
  health: 'Health',
  eye: 'Health',
  dental: 'Health',
  dentist: 'Health',
  spectacles: 'Health',
  glasses: 'Health',

  // ── Education ──────────────────────────────────────────────
  book: 'Education',
  books: 'Education',
  notebook: 'Education',
  stationery: 'Education',
  pen: 'Education',
  pencil: 'Education',
  eraser: 'Education',
  course: 'Education',
  fees: 'Education',
  tuition: 'Education',
  coaching: 'Education',
  class: 'Education',
  exam: 'Education',
  college: 'Education',
  school: 'Education',
  university: 'Education',
  library: 'Education',
  udemy: 'Education',
  coursera: 'Education',
  unacademy: 'Education',
  byjus: 'Education',
  vedantu: 'Education',
  jee: 'Education',
  neet: 'Education',
  upsc: 'Education',
  printout: 'Education',
  printing: 'Education',
  photocopy: 'Education',
  xerox: 'Education',
  syllabus: 'Education',
  assignment: 'Education',

  // ── Shopping ───────────────────────────────────────────────
  clothes: 'Shopping',
  clothing: 'Shopping',
  shirt: 'Shopping',
  jeans: 'Shopping',
  kurta: 'Shopping',
  saree: 'Shopping',
  shoes: 'Shopping',
  sandals: 'Shopping',
  slippers: 'Shopping',
  bag: 'Shopping',
  watch: 'Shopping',
  amazon: 'Shopping',
  flipkart: 'Shopping',
  myntra: 'Shopping',
  ajio: 'Shopping',
  meesho: 'Shopping',
  nykaa: 'Shopping',
  zara: 'Shopping',
  'h&m': 'Shopping',
  westside: 'Shopping',
  pantaloons: 'Shopping',
  hm: 'Shopping',
  fashion: 'Shopping',
  mall: 'Shopping',
  dress: 'Shopping',
  jacket: 'Shopping',
  accessories: 'Shopping',
  jewellery: 'Shopping',
  earrings: 'Shopping',
  cosmetics: 'Shopping',
  makeup: 'Shopping',
  perfume: 'Shopping',
  beauty: 'Shopping',
  skincare: 'Shopping',
  haircare: 'Shopping',
  shampoo: 'Shopping',
  conditioner: 'Shopping',
  soap: 'Shopping',
  lotion: 'Shopping',
  facewash: 'Shopping',
  toothpaste: 'Shopping',
  toothbrush: 'Shopping',

  // ── Entertainment ──────────────────────────────────────────
  movie: 'Entertainment',
  cinema: 'Entertainment',
  pvr: 'Entertainment',
  inox: 'Entertainment',
  bookmyshow: 'Entertainment',
  netflix: 'Entertainment',
  hotstar: 'Entertainment',
  prime: 'Entertainment',
  spotify: 'Entertainment',
  youtube: 'Entertainment',
  gaming: 'Entertainment',
  game: 'Entertainment',
  steam: 'Entertainment',
  playstation: 'Entertainment',
  xbox: 'Entertainment',
  concert: 'Entertainment',
  show: 'Entertainment',
  theatre: 'Entertainment',
  outing: 'Entertainment',
  park: 'Entertainment',
  zoo: 'Entertainment',
  funzone: 'Entertainment',
  bowling: 'Entertainment',
  cricket: 'Entertainment',
  football: 'Entertainment',
  match: 'Entertainment',
  sports: 'Entertainment',
  subscription: 'Entertainment',

  // ── Utilities ──────────────────────────────────────────────
  electricity: 'Utilities',
  electric: 'Utilities',
  bill: 'Utilities',
  wifi: 'Utilities',
  internet: 'Utilities',
  broadband: 'Utilities',
  airtel: 'Utilities',
  jio: 'Utilities',
  bsnl: 'Utilities',
  vi: 'Utilities',
  vodafone: 'Utilities',
  recharge: 'Utilities',
  mobile: 'Utilities',
  phone: 'Utilities',
  gas: 'Utilities',
  lpg: 'Utilities',
  indane: 'Utilities',
  cylinder: 'Utilities',
  waterutil: 'Utilities',
  maintenance: 'Utilities',
  society: 'Utilities',
  cable: 'Utilities',
  dth: 'Utilities',
  tatasky: 'Utilities',
  dish: 'Utilities',

  // ── Rent ───────────────────────────────────────────────────
  rent: 'Rent',
  landlord: 'Rent',
  pg: 'Rent',
  hostel: 'Rent',
  room: 'Rent',
  flat: 'Rent',
  accommodation: 'Rent',
  deposit: 'Rent',
  lease: 'Rent',
  housing: 'Rent',

  // ── Other ──────────────────────────────────────────────────
  gift: 'Other',
  donation: 'Other',
  charity: 'Other',
  atm: 'Other',
  bank: 'Other',
  fine: 'Other',
  fee: 'Other',
  misc: 'Other',
  miscellaneous: 'Other',
  transfer: 'Other',
  loan: 'Other',
  emi: 'Other',
  insurance: 'Other',
  investment: 'Other',
};

/**
 * Given a title string, returns the best matching Category (or null if no match found).
 *
 * Matching strategy (in order of priority):
 * 1. Exact full-string match against keyword map
 * 2. Exact per-token match
 * 3. Prefix match — only if the token is 4+ chars AND a keyword starts with it
 *    (avoids false positives like "bi" → "bill")
 */
export function suggestCategory(title: string): Category | null {
  if (!title || title.trim().length < 2) return null;

  const lower = title.toLowerCase().trim();

  // 1. Exact full-string match
  if (KEYWORD_MAP[lower]) return KEYWORD_MAP[lower];

  // 2. Tokenize the input
  const tokens = lower.split(/[\s,_\-/()]+/).filter(t => t.length >= 2);

  for (const token of tokens) {
    // 2a. Exact token match (any length >= 2)
    if (KEYWORD_MAP[token]) return KEYWORD_MAP[token];

    // 2b. Prefix match — token must be >= 4 chars to avoid false positives
    if (token.length >= 4) {
      for (const keyword of Object.keys(KEYWORD_MAP)) {
        // token starts with a keyword (e.g. "strepsils" starts with "strepsil")
        if (token.startsWith(keyword) && keyword.length >= 3) {
          return KEYWORD_MAP[keyword];
        }
        // keyword starts with token (e.g. keyword "strepsils" starts with "strep")
        if (keyword.startsWith(token) && token.length >= 4) {
          return KEYWORD_MAP[keyword];
        }
      }
    }
  }

  return null;
}
